name: forex strategy 1 pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  run_analysis:
    runs-on: windows-latest
    permissions:
      contents: write
      actions: write
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Python path
      run: |
        echo "${{ github.workspace }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "PYTHONPATH=${{ github.workspace }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Run labels generation
      run: |
        python -c "import sys; print(sys.path)"
        python scripts/01_labels_strat1.py
      shell: pwsh

    - name: Train all models
      if: success()
      run: python scripts/02_allmodels_strat1.py
      shell: pwsh

    - name: Select best models
      if: success()
      run: python scripts/03_bestmodels_strat1.py
      shell: pwsh

    - name: Run predictions
      if: success()
      run: python scripts/04_predictions_strat1.py
      shell: pwsh

    - name: Run metrics
      if: success()
      run: python scripts/05_metrics_strat1.py
      shell: pwsh

    - name: Check for output changes
      id: check_changes
      run: |
        git diff --quiet output/ || echo "changed=true" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Commit and push output files
      if: env.changed == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/*
        git commit -m "Update analysis results [skip ci]"
        git push
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: forex-analysis-output
        path: output/