# .github/workflows/forex_strategy_pipeline.yml
name: Forex Strategy 1 Pipeline

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      strategy_id:
        description: 'Strategy 1'
        required: true
        default: 'strat1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.strategy_id }}
  cancel-in-progress: false

jobs:
  forex_analysis:
    runs-on: window-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache forex data
      uses: actions/cache@v3
      with:
        path: forex_data
        key: ${{ runner.os }}-forex-data-${{ hashFiles('forex_data/**') }}
        restore-keys: |
          ${{ runner.os }}-forex-data-

    - name: Run workflow orchestrator
      run: |
        python workflow_orchestrator.py
      env:
        STRATEGY_ID: ${{ inputs.strategy_id }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: forex-analysis-results-${{ inputs.strategy_id }}
        path: |
          output/
          logs/
        retention-days: 7