name: forex strategy 1 pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  generate_labels:
    runs-on: windows-latest
    needs: prepare
    steps:
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: List scripts directory
        run: dir ${{ github.workspace }}/scripts

      - name: Run labels generation
        run: python ${{ github.workspace }}/scripts/01_labels_strat1.py
        shell: pwsh

      - name: Upload labels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: labels-output
          path: output/

  train_models:
    runs-on: windows-latest
    needs: generate_labels
    steps:
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Train all models
        run: python scripts/02_allmodels_strat1.py
        shell: pwsh

      - name: Upload models as artifact
        uses: actions/upload-artifact@v3
        with:
          name: models-output
          path: output/

  select_best_models:
    runs-on: windows-latest
    needs: train_models
    steps:
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Select best models
        run: python scripts/03_bestmodels_strat1.py
        shell: pwsh

      - name: Upload best models as artifact
        uses: actions/upload-artifact@v3
        with:
          name: best-models-output
          path: output/

  run_predictions:
    runs-on: windows-latest
    needs: select_best_models
    steps:
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run predictions
        run: python scripts/04_predictions_strat1.py
        shell: pwsh

      - name: Upload predictions as artifact
        uses: actions/upload-artifact@v3
        with:
          name: predictions-output
          path: output/

  run_metrics:
    runs-on: windows-latest
    needs: run_predictions
    steps:
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run metrics
        run: python scripts/05_metrics_strat1.py
        shell: pwsh

      - name: Upload metrics as artifact
        uses: actions/upload-artifact@v3
        with:
          name: metrics-output
          path: output/
