name: forex strategy 1 pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: windows-latest
    outputs:
      cache_key: ${{ steps.cache_key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - id: cache_key
        run: echo "key=${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4

      - name: Upload cache key as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cache-key
          path: $GITHUB_OUTPUT

  generate_labels:
    runs-on: windows-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4

      - name: Download cache key artifact
        uses: actions/download-artifact@v3
        with:
          name: cache-key

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run labels generation
        run: python scripts/01_labels_strat1.py
        shell: pwsh

      - name: Upload labels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: labels-output
          path: output/

  train_models:
    runs-on: windows-latest
    needs: generate_labels
    steps:
      - uses: actions/checkout@v4

      - name: Download labels artifact
        uses: actions/download-artifact@v3
        with:
          name: labels-output

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Train all models
        run: python scripts/02_allmodels_strat1.py
        shell: pwsh

      - name: Upload models as artifact
        uses: actions/upload-artifact@v3
        with:
          name: models-output
          path: output/

  select_best_models:
    runs-on: windows-latest
    needs: train_models
    steps:
      - uses: actions/checkout@v4

      - name: Download models artifact
        uses: actions/download-artifact@v3
        with:
          name: models-output

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Select best models
        run: python scripts/03_bestmodels_strat1.py
        shell: pwsh

      - name: Upload best models as artifact
        uses: actions/upload-artifact@v3
        with:
          name: best-models-output
          path: output/

  run_predictions:
    runs-on: windows-latest
    needs: select_best_models
    steps:
      - uses: actions/checkout@v4

      - name: Download best models artifact
        uses: actions/download-artifact@v3
        with:
          name: best-models-output

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run predictions
        run: python scripts/04_predictions_strat1.py
        shell: pwsh

      - name: Upload predictions as artifact
        uses: actions/upload-artifact@v3
        with:
          name: predictions-output
          path: output/
          
  run_metrics:
    runs-on: windows-latest
    needs: run_predictions
    steps:
      - uses: actions/checkout@v3

      - name: Download predictions artifact
        uses: actions/download-artifact@v3
        with:
          name: predictions-output

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run metrics
        run: python scripts/05_metrics_strat1.py
        shell: pwsh

      - name: Upload metrics as artifact
        uses: actions/upload-artifact@v3
        with:
          name: metrics-output
          path: output/
