name: forex strategy 1 pipeline
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run_analysis:
    runs-on: windows-latest
    permissions:
      contents: write
      actions: write
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: install dependencies
      run: |
        if [ -f requirements.txt ]; then 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        fi

    - name: run labels generation
      run: |
        python scripts\01_labels_strat1.py

    - name: train all models
      run: |
        python scripts\02_allmodels_strat1.py

    - name: select best models
      run: |
        python scripts\03_bestmodels_strat1.py

    - name: run predictions
      run: |
        python scripts\04_predictions_strat1.py

    - name: run metrics
      run: |
        python scripts\05_metrics_strat1.py

    - name: check for output changes
      id: output_files
      run: |
        if git diff --quiet output\; then
          echo "::set-output name=changed::false"
        else
          echo "::set-output name=changed::true"
        fi

    - name: commit and push output files
      if: success() && steps.output_files.outputs.changed == 'true'
      run: |
        git config --global user.name "github action"
        git config --global user.email "kalulu404@gmail.com"
        git add output\*
        git commit -m "add analysis results [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: upload output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: forex-analysis-output
        path: output\