jobs:
  run_script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create output directory if not exists
      run: |
        if (-not (Test-Path -Path "output")) {
          New-Item -ItemType Directory -Path "output"
          Write-Host "Output directory created."
        } else {
          Write-Host "Output directory already exists."
        }

    - name: Run Python script
      run: |
        python scripts/labels_strat1.py
