name: Create labels

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  process_data:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Prepare directories
      run: |
        mkdir -p output/labels_strat1
      shell: bash
    
    - name: Run data processing
      run: python scripts/labels_strat1.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: processed-data
        path: output/labels_strat1/
        retention-days: 7